spring:
  application:
    name: web端
  mvc:
    static-path-pattern: /**
    #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sfd_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
server:
  port: 9999
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /
  tomcat:
    basedir: /home/zhangds/tmp
logging:
  config: classpath:logback-boot.xml
  level:
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


